name: Test
on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  test:
    name: test py${{ matrix.python-version }} on linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
      - run: source $HOME/.poetry/env; poetry install
      - run: source $HOME/.poetry/env; poetry run pytest -vvv